/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.50
 * Generated at: 2018-06-23 09:51:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1528529187177L));
    _jspx_dependants.put("jar:file:/D:/forGit/Study/HTML/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/ResponsiveWebMake/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, false, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE HTML>\n");
      out.write("<html lang=\"ko\">\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1, user-scalable=no\">\n");
      out.write("<title>Document</title>\n");
      out.write("<style>\n");
      out.write("*{margin:0; padding:0;}\n");
      out.write("\n");
      out.write("#wrap{\n");
      out.write("display:flex;\n");
      out.write("flex-flow:row wrap;\n");
      out.write("width:90%; \n");
      out.write("margin:0 auto;\n");
      out.write("}\n");
      out.write(".header{\n");
      out.write("display:flex;\n");
      out.write("order:1;\n");
      out.write("position:relative;\n");
      out.write("width:100%;\n");
      out.write("justify-content:flex-end;\n");
      out.write("}\n");
      out.write(".header h1{\n");
      out.write("position:absolute;\n");
      out.write("top:0;\n");
      out.write("left:0;\n");
      out.write("width:12.5%;\n");
      out.write("height:142px;\n");
      out.write("background:#ff6b57;\n");
      out.write("}\n");
      out.write(".header nav{\n");
      out.write("width:87.5%;\n");
      out.write("min-height:80px;\n");
      out.write("background:#ff6b57;\n");
      out.write("}\n");
      out.write(".slider_section{\n");
      out.write("order:2;\n");
      out.write("width:50%;\n");
      out.write("background:#3c90be;\n");
      out.write("}\n");
      out.write(".gallery_section{\n");
      out.write("order:3;\n");
      out.write("width:27.08333333333%;\n");
      out.write("height:440px;\n");
      out.write("background:#f8de73;\n");
      out.write("}\n");
      out.write(".rankup_section{\n");
      out.write("order:4;\n");
      out.write("width:22.9166666667%;\n");
      out.write("background:#00d2a5;\n");
      out.write("}\n");
      out.write(".latest_post_section{\n");
      out.write("order:5;\n");
      out.write("width:30%;\n");
      out.write("background:#9cabe4;\n");
      out.write("}\n");
      out.write(".popular_post_section{\n");
      out.write("order:6;\n");
      out.write("width:30%;\n");
      out.write("background:#d76817;\n");
      out.write("}\n");
      out.write(".banner_section{\n");
      out.write("display:flex;\n");
      out.write("order:7;\n");
      out.write("flex-flow:column nowrap;\n");
      out.write("width:22.91666667%;\n");
      out.write("}\n");
      out.write(".banner_section div{\n");
      out.write("flex:1 1 0;\n");
      out.write("}\n");
      out.write(".banner_section div.banner_box_01{\n");
      out.write("background:#0175bb;\n");
      out.write("}\n");
      out.write(".banner_section div.banner_box_02{\n");
      out.write("background:#1261c9;\n");
      out.write("}\n");
      out.write(".social_section{\n");
      out.write("order:8;\n");
      out.write("width:17.08333333%;\n");
      out.write("height:270px;\n");
      out.write("background:#fe6eda;\n");
      out.write("}\n");
      out.write(".footer{\n");
      out.write("order:9;\n");
      out.write("width:100%;\n");
      out.write("height:94px;\n");
      out.write("background:#474747;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t<div id=\"wrap\">\n");
      out.write("\t\t<header class=\"header\">\n");
      out.write("\t\t\t<h1></h1>\n");
      out.write("\t\t\t<nav></nav>\n");
      out.write("\t\t</header>\n");
      out.write("\t\t<section class=\"slider_section\"></section>\n");
      out.write("\t\t<section class=\"gallery_section\"></section>\n");
      out.write("\t\t<section class=\"rankup_section\"></section>\n");
      out.write("\t\t\n");
      out.write("\t\t<section class=\"latest_post_section\"></section>\n");
      out.write("\t\t<section class=\"popular_post_section\"></section>\n");
      out.write("\t\t<section class=\"banner_section\">\n");
      out.write("\t\t\t<div class=\"banner_box_01\"></div>\n");
      out.write("\t\t\t<div class=\"banner_box_02\"></div>\n");
      out.write("\t\t</section>\n");
      out.write("\t\t<section class=\"social_section\"></section>\n");
      out.write("\t\t<footer class=\"footer\"></footer>\n");
      out.write("\t</div>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
