/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.50
 * Generated at: 2018-07-14 10:01:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.login;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<meta name=\"description\" content=\"\">\r\n");
      out.write("<meta name=\"author\" content=\"\">\r\n");
      out.write("<title>로그인</title>\r\n");
      out.write("<!-- Bootstrap Core CSS -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\">\r\n");
      out.write("<link href=\"resources/css/mainboard.css\" rel=\"stylesheet\">\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"http://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\"></script>\r\n");
      out.write("<!-- Custom CSS -->\r\n");
      out.write("<link href=\"resources/css/postodo.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$(document).ready(function() {\r\n");
      out.write("\t$('#loginButton').click(function() {\r\n");
      out.write("\t\tlogin();\r\n");
      out.write("\t}); \r\n");
      out.write("\t\r\n");
      out.write("\tfunction login() {\r\n");
      out.write("\t\tvar formData = $('#formLogin').serialize();\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl : \"doLogin.do\"\r\n");
      out.write("\t\t\t, type : 'POST'\r\n");
      out.write("\t\t\t, contentType : 'application/x-www-form-urlencoded; charset=UTF-8'\r\n");
      out.write("\t\t\t, context : this\r\n");
      out.write("\t\t\t, data : formData\r\n");
      out.write("\t\t\t, dataType : 'json'\r\n");
      out.write("\t\t\t, beforeSend : function() {\r\n");
      out.write("\t\t\t\t$('.wrap-loading').removeClass('display-none');\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t, success : function(data) {\r\n");
      out.write("\t\t\t\tvar result = data.loginResult;\r\n");
      out.write("\t\t\t\tconsole.dir(data);\r\n");
      out.write("\t\t\t\tconsole.log(result);\r\n");
      out.write("\t\t\t\tif (result == 1) {\r\n");
      out.write("\t\t\t\t\talert(\"로그인 성공\");\t\r\n");
      out.write("\t\t\t\t\twindow.location.href = \"board/callFreeboard.html\";\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\talert(\"로그인 실패\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t, complete : function() {\r\n");
      out.write("\t\t\t\t$('.wrap-loading').addClass('display-none');\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t, error : function() {\r\n");
      out.write("\t\t\t\t$('.wrap-loading').addClass('display-none');\r\n");
      out.write("\t\t\t\talert('오류가 발생했습니다.');\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"loginBody\">\r\n");
      out.write("\r\n");
      out.write("<!-- middle page//S -->\r\n");
      out.write("<div class=\"container-full middlePageLogin\">\r\n");
      out.write("\t<div class=\"wrap-loading display-none\"><div><img src=\"resources/image/ajax_loading.gif\" /></div></div>\r\n");
      out.write("\t<!-- page header//S -->\r\n");
      out.write("\t<div class=\"page-header\">\r\n");
      out.write("\t\t<h1 class=\"logoLogin\">Postodo <small>환영합니다!</small>&nbsp;&nbsp;<!-- <a href=\"../homepage/homepage.html\" style=\"font-size: 12px; color: white;\">홈페이지 구경하실래요?</a> --></h1>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- page header//E -->\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- panel//S -->\r\n");
      out.write("\t<div class=\"panel panel-info\">\r\n");
      out.write("\t\t<div class=\"panel-heading\">\r\n");
      out.write("\t\t\t<h3 class=\"panel-title\">로그인하세요.</h3>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- panel body//S -->\r\n");
      out.write("\t\t<div class=\"panel-body\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<!-- col//S -->\r\n");
      out.write("\t\t\t\t<!-- <div class=\"col-md-5\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#\"><img src=\"http://techulus.com/buttons/fb.png\" /></a><br/>\r\n");
      out.write("\t\t\t\t\t<a href=\"#\"><img src=\"http://techulus.com/buttons/tw.png\"/></a><br/>\r\n");
      out.write("\t\t\t\t\t<a href=\"#\"><img src=\"http://techulus.com/buttons/gplus.png\"/></a>\r\n");
      out.write("\t\t\t\t</div> -->\r\n");
      out.write("\t\t\t\t<!-- col//E -->\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<!-- col-md-7//S -->\r\n");
      out.write("\t\t\t\t<div class=\"col-md-10\" style=\"border-left:1px solid #ccc; height:160px;\">\r\n");
      out.write("\t\t\t\t\t<form id=\"formLogin\" class=\"form-horizontal\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t<fieldset>\r\n");
      out.write("\t\t\t\t\t\t\t<input id=\"textinput\" name=\"userId\" type=\"text\" placeholder=\"사용자 ID를 입력하세요.\" class=\"form-control input-md\" value=\"superadmin\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"spacingLogin\"><input type=\"checkbox\" name=\"checkboxes\" id=\"checkboxes-0\" value=\"1\"><small>ID 기억하기</small></div>\r\n");
      out.write("\t\t\t\t\t\t\t<input id=\"textinput\" name=\"userPassword\" type=\"password\" placeholder=\"사용자 비밀번호를 입력하세요.\" class=\"form-control input-md\" value=\"1234\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"spacingLogin\"><a href=\"#\"><small>비밀번호를 잊어버리셨나요?</small></a><br/><a href=\"#\"><small>처음이신가요?</small></a></div>\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</fieldset>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- col-md-7//E -->\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<!-- col//S -->\r\n");
      out.write("\t\t\t\t<div class=\"col-md-2\">\r\n");
      out.write("\t\t\t\t\t<button id=\"loginButton\" name=\"loginButton\" class=\"btn btn-info btn-bg\">로그인</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- col//E -->\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- panel body//E -->\r\n");
      out.write("\t\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- panel//E -->\r\n");
      out.write("\t<p class=\"pLogin\"><a href=\"#\">About</a> AACII</p>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- middle page//E -->\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>   ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
